### ISSUE TITLE
Create orders serializer

### ISSUE THREAD

**Issue by sales-ls21** [PythonPonies/bangazon-api#19]
### Context
Create orders serializer.
1. What should the feature do?
**This should store order associated information in JSON format. All information associated with the orders model should be serialized.**

2. When and where should the feature appear?
**Adjustments should be made to a serializers.py file and documented with the appropriate associated model name.** 
### Associated Product Ticket
#1 
### Process
1. Potential Impact on Code or Other Features
**This code is required in order to make the convert data from user input and to respond to user requests to the API in JSON format.** 
2. Suggested Implementation
**The use of modelserializers is highly recommended to avoid redundant code.** 
### Expected Result
**This code should be tested to confirm that it both receives and return JSON formatted data that corresponds to information in each of the database models.**

**Comment by ZoeLeBlanc** [comment]
Ended up creating a hyperlinked model serializer for our client. Serializer is working even with primary keys. Everything is merged in. Closing issue
