### ISSUE TITLE
Develop Questions for Product Manager

### ISSUE THREAD

**Issue by ZoeLeBlanc** [PythonPonies/bangazon-api#3]
### Context
1. What should the feature do?
- We need to come up with a set of questions to flesh out the product ticket we received
2. When and where should the feature appear?

### Associated Product Ticket
#1 
Story
  As a client software developer
  In order to access Bangazon resource
  I want to have access to the Bangazon API

Scenarios
  Given that a client developer is writing a client for Bangazon
  When the developer requests the root API URL
  Then a list of all available resources for the API should be provided

### Process
1. Potential Impact on Code or Other Features
2. Suggested Implementation

**Comment by sales-ls21** [comment]
1.	What the hell is the product?
2.	What information do you need from API?
3.	What format should data be in? (JSON/XML/etc)
4.	Authorization? If so, are there levels of permission? What is required for authorization?
5.	Using CLI or GUI to access?
6.	What are the categories of the product?
7.	What is timeline?
8.	What is the target audience?
9.	Are suggestions welcome?
10.	Big picture overview?
11.	What methods are allowed on the APIs?
12.  Error handling?

**Comment by ZoeLeBlanc** [comment]
### Notes from VP Steve: 

Product owner has priority. We do not have ownership but can offer suggestions.

### Notes from Product Manager Steve:
- e-commerce platform for individuals
- anybody can build a product on our platform
- people selling products to people (personal e-commerce)
- craigslist and amazon smashed together, people to people marketplace, with user experience

- need a minimally viable API, request all the resources
  - nice RESTful API, can query any one of those resources and build a piece of software on those resources.
  - needs to be flexible interaction with resources
  - internal tracking (employees, computers)
  - get without authorization, but rest of the methods needs authorization
  - flow of api through hyperlinks
  - data in json format
  - first iteration, expose all endpoints
- everything needed for buying and selling
  - customer, payment methods, products, orders
  - create categories or from default categories
  - can be both seller and buyer
  - orders can have more than one product
  - when a customer signs up is saved, but not their overall activity 
  - save each product, even if duplicate
  - no user ratings
  - no returns
  -no limits on product types
- no user interface
- no deadline
- no need for editing for MVP
- customer service app to track orders for internally
- first and last name of other users only thing available
- search, but not top priority
- url is the name of the resource
- no deployments currently
- 100% knowledge of each block of code for each team member

**Comment by jokirby** [comment]
django restful api
users only know each others: first, last name

JSON
NO UNIT TESTING

Product
-Create or pick from categories, one category
-name
-user FK

Users
-first name
-last name
-sign up date
-shipping address
-billing address
-payment type
-credit card #
-products they’ve sold
-current products
-total # of orders

Orders
-product FK
-buyer FK
-buyer first
-buyer last
-seller FK
-seller first
-seller last
