### ISSUE TITLE
Route the base model for the api to its view

### ISSUE THREAD

**Issue by nathantbaker** [PythonPonies/bangazon-api#39]
### Context
**1. What should the feature do?**
The model associated with the api's root path should be routed to its corresponding view so that when a user requests resources at root url, all resources are listed out.

**2. When and where should the feature appear?**
You can test the routing by going to the root path: `http://127.0.0.1:8000/` 

### Associated Product Ticket
#1 
### Process
**1. Potential Impact on Code or Other Features**
We need to communicate well about updating the urls.py file to avoid merge conflicts.

**2. Suggested Implementation**
The `urls.py` file should be updated. I'm guessing the routing for the root url wil lbe similar to the following format, but I'm not sure:

`^/$ Name: 'root'`

### Expected Result
This should allow a user to get user data in JSON format when accessing the root URL.

**Comment by ZoeLeBlanc** [comment]
Ended up not needing to route the api view because default router. Fix is merged in. Closing issue
