### ISSUE TITLE
Create Django App

### ISSUE THREAD

**Issue by ZoeLeBlanc** [PythonPonies/bangazon-api#4]
### Context
1. What should the feature do?
  We need to create our initial Django app, should be named _bangazon-api_
2. When and where should the feature appear?
  
### Associated Product Ticket
#1 Initial Product Ticket 

### Process
1. Potential Impact on Code or Other Features
  Initial foundation for all code.
2. Suggested Implementation
- [ ]  Mockup initial file structure
- [ ] Start app locally and merge into  master

### Expected Result
Should be able to run on everyone's local computer after pushed up and merged into master branch.

**Comment by sales-ls21** [comment]
App is up and running.
