### ISSUE TITLE
Create Order Model

### ISSUE THREAD

**Issue by stevenwally** [PythonPonies/bangazon-api#49]
### Context
1. What should the feature do?
**The Order model is the endpoint for accessing any of its associated data and properties.**
2. When and where should the feature appear?
**Upon requesting the Order data endpoint, client will have access to the data associated with given Order.**

### Process
1. Potential Impact on Code or Other Features
**This will enable other models (parts of the database) to access certain properties of the Order model. This model will have a corresponding view and serializer**
2. Suggested Implementation
_[to be added to models.py]_

Create class 'Order'

Define properties of User and corresponding field types:

- orderId [Primary Key]
- date_created [DateField.auto_now]
- buyerId [Foreign Key - buyer]
- payment_type [Foreign Key]
- complete [Boolean - True/False]

### Expected Result
**A database table allowing access to client of the associated Order data therein**

**Comment by ZoeLeBlanc** [comment]
Now working and merged into master. closing issue.
