### ISSUE TITLE
Create ProductOnOrder Model

### ISSUE THREAD

**Issue by stevenwally** [PythonPonies/bangazon-api#51]
### Context
1. What should the feature do?
**The ProductOnOrder model is the endpoint for accessing any of its associated data and properties.**
2. When and where should the feature appear?
**Upon requesting the ProductOnOrder data endpoint, client will have access to the data associated with it.**

### Process
1. Potential Impact on Code or Other Features
**This will enable other models (parts of the database) to access certain properties of the ProductOnOrder model. This model will have a corresponding view and serializer**
2. Suggested Implementation
_[to be added to models.py]_

Create class 'ProductOnOrder'

Define properties of ProductOnOrder and corresponding field types:

- pooId [Primary Key - generated by Django]
- productId [Foreign Key]
- orderId [Foreign Key]

### Expected Result
**A database table allowing access to client of the associated ProductOnOrder data therein**

**Comment by ZoeLeBlanc** [comment]
Checkout Django docs on many to many foreign key relationships. Decide if we want a model or use the relationship fields.
