### ISSUE TITLE
Create ERD

### ISSUE THREAD

**Issue by sales-ls21** [PythonPonies/bangazon-api#6]
### Context
An ERD is needed to plan the building of the SQLite database that will store API data. 

1. What should the feature do?
ERD should map relationship between the various categories of data utilizing foreign keys and join tables as necessary. This will be used to construct actual database. 

2. When and where should the feature appear?
ERD needs to be developed before any work is done on constructing the actual database, but after the initial conversation with product owner. The feature will not be a permanent part of the app, but will be a planning tool.

### Associated Product Ticket
#1 Initial product ticket submitted 

### Process
1. Potential Impact on Code or Other Features
ERD is required before any work is done on database setup.

2. Suggested Implementation
Draw.io or a team whiteboard session.

### Expected Result
A complete ERD that can be used to construct database.

**Comment by ZoeLeBlanc** [comment]
![bangazon_api](https://cloud.githubusercontent.com/assets/8355129/22224335/db77b338-e183-11e6-96e3-9c6806648d5e.png)

**Comment by nathantbaker** [comment]
via steve minus the picture in Products
