### ISSUE TITLE
Create Basic User Serializer

### ISSUE THREAD

**Issue by sales-ls21** [PythonPonies/bangazon-api#71]
### Context
1. What should the feature do?
Feature should define a new query set that only includes allowed data from the user table (id, first name, last name).
2. When and where should the feature appear?
Feature should be included in the serializers.py file and be linked to the current query set such that logic can be written to determine which query set is displayed after determining a user's permission.
### Associated Product Ticket
#64 Protect customer provide information
### Process
1. Potential Impact on Code or Other Features
This would require a refactor of the user serializer. 
2. Suggested Implementation
Create new serializer and restrict displayed data to id, first name, last name. 
### Expected Result
This should create a new query set that can be displayed based on a requester's level of permission.

**Comment by ZoeLeBlanc** [comment]
Created new basic serializer and it works. SEND
