### ISSUE TITLE
Refactor User View

### ISSUE THREAD

**Issue by stevenwally** [PythonPonies/bangazon-api#73]
### Context
1. What should the feature do?
The refactored user view should allow unauthenticated user to READ ONLY other user's first name, last name, and user id. If a user is authenticated*, then all user data can be accessed.

*Currently, the only form of authentication will be admin status.

2. When and where should the feature appear?
The refactored user view appears when a user requests the 'User' endpoint from the root API.

### Process
1. Potential Impact on Code or Other Features
The refactored user view will depend on other code additions in order to fulfill the specifications of the product ticket concerned:
- Global permissions will need to be set in regards to a user's authentication.
- A new serializer will be necessary to return only user's first name, last name, and user id - for when the requesting user is unauthenticated.

2. Suggested Implementation
Upon request of User endpoint, check for authentication. 

If user is authenticated, implement logic that sets serializer class to return all User data.

If user is not authenticated, implement logic that sets serializer class to return only first name, last name, and user id data.

### Expected Result

Upon full implementation, if a user is authenticated and requests User endpoint, all data related to the User endpoint will be accessible.

Conversely, if a user is not authenticated and requests User endpoint, only first name, last name, and user id data will be returned.

**Comment by ZoeLeBlanc** [comment]
knocked this awesome ticket out of the park ;). SEND
