### ISSUE TITLE
Authentication is required to view first/last name, name id

### ISSUE THREAD

**Issue by nathantbaker** [PythonPonies/bangazon-api#75]
### Context
**1. What should the feature do?**
This change should create three levels of access to the API.

**2. When and where should the feature appear?**
The API should have three levels of access:
1. Someone not logged in should have access to nothing.
1. Someone logged in, but not an admin should have access to first name, last name and name id.
1. Some logged in who is an admin should see everything.

### Associated Product Ticket
#64 

### Process
**1. Potential Impact on Code or Other Features**
It's suggested to test that all levels of access work.

**2. Suggested Implementation**
The default authorization settings could be updated and each view may have a check that figures out what should be shown.

### Expected Result
1. Someone not logged in should have access to nothing. They should be shown a log in form.
1. Someone logged in, but not an admin should have access to first name, last name and name id.
1. Some logged in who is an admin should see everything.

**Comment by nathantbaker** [comment]
This technical ticket was created based on clarification after our stand-up with Steve.

**Comment by ZoeLeBlanc** [comment]
Working now. Closing
