### ISSUE TITLE
Update string methods to .format form. 

### ISSUE THREAD

**Issue by sales-ls21** [PythonPonies/bangazon-api#86]
### Context
1. What should the feature do?
All string methods on the models.py module should be converted to the .format method as noted here: https://docs.python.org/2/library/stdtypes.html#str.format. 

2. When and where should the feature appear?
These changes should be made on the models.py module in the bangazonapi folder. 

### Associated Product Ticket
#69 

### Process
1. Potential Impact on Code or Other Features
There should be no effect on any other code, but it should be run through the server to ensure that it continues to produce the strings on the associated tables. 

2. Suggested Implementation
A complete reference is in the included link.

### Expected Result
Code should perform exactly as it does now. No changes should be noticeable (i.e. the string names on the tables should still appear)

**Comment by ZoeLeBlanc** [comment]
Works great. CLOSE
