### ISSUE TITLE
Remove `__pycache__` directories

### ISSUE THREAD

**Issue by nathantbaker** [PythonPonies/bangazon-api#87]
### Context
**1. What should the feature do?**
Remove any `__pycache__` directories from the repo.

**2. When and where should the feature appear?**
There shouldn't be any `__pycache__` directories as they aren't needed.

### Associated Product Ticket
#69
### Process
**1. Potential Impact on Code or Other Features**
If the fix to this is merged and there is still cache on local computers, it might be get pushed up again by another person.
**2. Suggested Implementation**
Remove all  `__pycache__` directories. For a more permanent fix, we can check that .gitignore file is configured correctly to ensure cache isn't pushed up in the future.

### Expected Result
After correct code is deployed, you shouldn't see any `__pycache__` directories.

**Comment by sales-ls21** [comment]
Done!
