### ISSUE TITLE
Remove second return statement in Product_On_Order model

### ISSUE THREAD

**Issue by nathantbaker** [PythonPonies/bangazon-api#89]
2. Remove this line of code, as it is unreachable: 

### Context
**1. What should the feature do?**
We have redundant line of code. It can be deleted.
**2. When and where should the feature appear?**
 There is a second return statement which is never being triggered [here](https://github.com/PythonPonies/bangazon-api/blob/587b8eb9ed64e5c61555678671bca6141bf7a6d9/bangazon/bangazonapi/models.py#L112).
### Associated Product Ticket
#69 

### Process
**1. Potential Impact on Code or Other Features**
None
**2. Suggested Implementation**
Remove that redundant line

### Expected Result
The app should work as it did before without any changes.

**Comment by ZoeLeBlanc** [comment]
CLEANED IT OUT. SEND
