### ISSUE TITLE
Remove Unused Imported Methods from views.py

### ISSUE THREAD

**Issue by stevenwally** [PythonPonies/bangazon-api#90]
6. These authentication methods are being imported, but not being used. Please remove: https://github.com/PythonPonies/bangazon-api/blob/master/bangazon/bangazonapi/views.py#L8

### Context
**In views.py, the authentication methods SessionAuthentication, BasicAuthentication, TokenAuthentication are being imported, but not being used.**

**In addition, the filter methods that are being imported are also not being used.**

### Associated Product Ticket
Not applicable (most recent of relevance is #69).

### Process
1. Potential Impact on Code or Other Features
**Eliminates unused imported methods from code.**
2. Suggested Implementation
**Remove lines 6, 7 and 8 from views.py.**

### Expected Result
**Our imported methods will now reflect what methods are actually being utilized within our code.**

**Comment by ZoeLeBlanc** [comment]
NO MORE OLD IMPORTS. SEND
